export ALLOW_MISSING_DEPENDENCIES=true

export FOX_VANILLA_BUILD=1
export FOX_AB_DEVICE=1
export FOX_VIRTUAL_AB_DEVICE=1
export OF_FORCE_PREBUILT_KERNEL=1
export FOX_BUILD_DEVICE=bangkk
export FOX_MAINTAINER_PATCH_VERSION=1
export OF_MAINTAINER="AkariOficial"

export FOX_ASH_IS_BASH=1
export FOX_USE_BASH_SHELL=1
export FOX_USE_NANO_EDITOR=1
export TW_DEFAULT_LANGUAGE="en"
export FOX_BUILD_DEVICE=bangkk
export LC_ALL="C"
export OF_IGNORE_LOGICAL_MOUNT_ERRORS=1
export OF_ENABLE_LPTOOLS=1

export OF_USE_GREEN_LED="0"
export FOX_DELETE_AROMAFM=1
export OF_ALLOW_DISABLE_NAVBAR=0

export FOX_USE_TAR_BINARY=1
export FOX_USE_SED_BINARY=1
export FOX_USE_XZ_UTILS=1
export FOX_USE_LZ4_BINARY=1
export FOX_USE_ZSTD_BINARY=1

export TARGET_SCREEN_WIDTH=1080
export TARGET_SCREEN_HEIGHT=2400

export TW_MAX_BRIGHTNESS=3929
export TW_DEFAULT_BRIGHTNESS=1023

export OF_SCREEN_H=2400
export OF_STATUS_H=85
export OF_STATUS_INDENT_LEFT=48
export OF_STATUS_INDENT_RIGHT=48
export OF_CLOCK_POS=1
