export FOX_ASH_IS_BASH=1
export FOX_USE_BASH_SHELL=1
export FOX_USE_NANO_EDITOR=1
export TW_DEFAULT_LANGUAGE="en"
export LC_ALL="C"
export OF_IGNORE_LOGICAL_MOUNT_ERRORS=1
export OF_ENABLE_LPTOOLS=1

export FOX_VIRTUAL_AB_DEVICE=1
#export FOX_RECOVERY_SYSTEM_PARTITION="/dev/block/mapper/system"
#export FOX_RECOVERY_VENDOR_PARTITION="/dev/block/mapper/vendor"

export OF_USE_GREEN_LED="0"
export FOX_DELETE_AROMAFM=1
export OF_ALLOW_DISABLE_NAVBAR=0

export FOX_USE_TAR_BINARY=1
export FOX_USE_SED_BINARY=1
export FOX_USE_XZ_UTILS=1
export FOX_USE_LZ4_BINARY=1
export FOX_USE_ZSTD_BINARY=1

export FOX_MAINTAINER_PATCH_VERSION=R11.1_0
export OF_MAINTAINER=akarizao

export OF_SCREEN_H=2400
export OF_STATUS_H=85
export OF_STATUS_INDENT_LEFT=48
export OF_STATUS_INDENT_RIGHT=48
export OF_CLOCK_POS=1
